return {  
 -- Event:
    CRAFT_EVENT = {"Anti Bee Egg", "Gem Egg", "Gem Chest"},
    BUY_TRAVELING_MERCHANT = { "Bee Egg", "Paradise Egg", "Fall Egg", "Loquat", "Feijoa", "Pitcher Plant" },
	PLANT_EVENT_TREES = true,
  
    MAX_PLANTS = 150,
    DESTROY_UNTIL_MIN_PLANTS = 100,
    DELETE_PLANTS_AFTER_MAX = {},
    KEEP_SEEDS = { "Bone Blossom" },
    KEEP_SEEDS_AFTER_MAX_PLANTS = {"Strawberry"},

    PLACE_COSMETIC = { "Cooking Kit" },
    
    -- General:
    AUTO_UPDATE_RESTART = true,
    REDEEM_CODES = {},
    EXTRA_PET_SLOTS = 3,
    EXTRA_EGG_SLOTS = 5,
    EXTRA_PET_INVENTORY_SLOTS = 1,
    MAX_REBIRTH_SHECKLES = 0,
    ADD_FRIEND = false,
    OPEN_ALL_SEED_PACK = true,
    COLLECT_FRUIT_PER_SECOND = 5,

    BUY_COSMETIC_SHOP = { ["Cooking Kit"] = 3 },

    BUY_EGGS = {
	["Common Egg"] = 100,
	"Jungle Egg",
	"Bug Egg",
	"Bee Egg",
	"Paradise Egg",
	"Mythical Egg",
	"Rare Summer Egg",
	"Common Summer Egg",
	"Rare Egg",
	"Uncommon Egg",
	"Gem Egg",
	"Fall Egg",},

    PLANT_EGGS = {
        "Gem Egg", 
        "Anti Bee Egg",
        "Spooky Egg",	
	"Safari Egg",
	"Bug Egg",
	"Paradise Egg",
	"Jungle Egg",
	"Fall Egg",
	"Enchanted Egg",
	"Sprout Egg",
	"Gourmet Egg",
	"Corrupted Zen Egg",
	"Zen Egg",
	"Dinosaur Egg",
	"Primal Egg",
	"Bee Egg",
	"Night Egg",
	"Mythical Egg",
	"Common Summer Egg",
	"Rare Egg",
	"Uncommon Egg"
	},
    
    BUY_SEED_SHOP = {
	"Octobloom Seed",
	"Zebrazinkle",
	"Crimson Thorn",
	"Romanesco",
	"Elder Strawberry",
	"Giant Pinecone",
	"Burning Bud",
	"Sugar Apple",
	"Ember Lily",
	"Beanstalk",
	"Sunflower",
	"Cacao",
	"Pepper",
	"Mushroom",
	"Grape",
	"Mango",
	"Dragon Fruit",
	"Cactus",
	["Coconut"] = 50,
	["Bamboo"] = 50,
	["Apple"] = 50,
	["Pumpkin"] = 50,
	["Watermelon"] = 50,
	"Daffodil",
	"Corn",
	["Tomato"] = 50,
	"Buttercup",
	["Blueberry"] = 50,
	["Strawberry"] = 50,
	"Carrot"
	},
  
LIMIT_PLANT_SEED = {
    ["Carrot"] = 10,
    ["Strawberry"] = 10,
    ["Blueberry"] = 10,
    ["Buttercup"] = 10,
    ["Tomato"] = 10,
    ["Corn"] = 10,
    ["Daffodil"] = 10,
    ["Watermelon"] = 10,
    ["Pumpkin"] = 10,
    ["Apple"] = 10,
    ["Bamboo"] = 10,
    ["Coconut"] = 10,
    ["Cactus"] = 10,
    ["Dragon Fruit"] = 10,
    ["Mango"] = 10,
    ["Grape"] = 10,
    ["Mushroom"] = 10,
    ["Pepper"] = 10,
    ["Cacao"] = 10,
    ["Sunflower"] = 10,
    ["Beanstalk"] = 10,
    ["Ember Lily"] = 10,
    ["Sugar Apple"] = 10,
    ["Burning Bud"] = 10,
    ["Giant Pinecone"] = 10,
    ["Elder Strawberry"] = 10,
    ["Romanesco"] = 10,},  -- { ["Plant Name"] = Plant Amount }

    FAVOURITE_FRUIT_MUTATIONS = {},  -- Stop Autosell
    SKIP_HARVEST_MUTATIONS = {},  -- Stop Harvest

    KEEP_PETS = {
    "Camel",
    ["Hydra"] = 10,
    "Lion",
    ["Magpie"] = 5,
    ["Pack Mule"] = 10,	
    "Chimera",
    "Bearded Dragon",
	"Goblin Miner",
	"Ruby Squid",
	"Diamond Panther",
	"Elephant",
	"Lich",
	"Mummy",
	"Hex Serpent",
	"Headless Horseman",
	"Reaper",
	["Ghost Bear"] = 8,
	"Fortune Squirrel",
	"Chinchilla",
	"Chubby Chipmunk",
	"Tiger",
    "Red Panda",
	"Barn Owl",
    "Swan",
	"Phoenix",
    "Cockatrice",
	"Griffin",
    "Golden Goose",
	"Lobster Thermidor",
	"French Fry Ferret",
	"Corrupted Kitsune",
	"Mizuchi",
    "Kitsune",
	"Spinosaurus",
    "Brontosaurus",
	"T-Rex",
    ["Seal"] = 3,
	"Fennec Fox",
    "Disco Bee",
	"Raccoon",
    "Queen Bee",
	"Dragonfly",
    "Butterfly",
	"Mimic Octopus",
    "Red Fox",
	"Golden Bee",
    "Firefly",
	"Chicken Zombie",
	"Ostrich",
	"Capybara",
    "Peacock",
	"Scarlet Macaw",
	"Moon Cat",
	"Geode Turtle",
	["Starfish"] = 12,
	["Rooster"] = 15,
	["Lich"] = 5,
	["Goat"] = 5,
	["Goblin"] = 5,
	["Crow"] = 5,
	},

    KEEP_PETS_WEIGHT = 7,
    KEEP_PETS_AGE = 75,
    EQUIP_PETS = {{"Starfish", 8, 1}, {"Capybara", 8, 2}, {"Rooster", 8, 3},},
    LEVELUP_LOLLIPOP_MIN_LEVEL = 90,
    USE_PETS_FOR_UPGRADE_SLOT = { "Starfish", "Capybara", "Rooster"},
    REMOVE_PET_MAX_UPGRADE = {"Starfish", "Capybara", "Golden Lab"},  -- Unequip from garden
  
    BUY_GEAR_SHOP = { "Grandmaster Sprinkler", "Master Sprinkler", "Godly Sprinkler", "Advanced Sprinkler", "Basic Sprinkler", ["Trading Ticket"] = 100, "Watering Can", "Levelup Lollipop" },
    USE_SPRINKLER = {},

    PET_WEBHOOK_URL = "",
    SEED_WEBHOOK_URL = "", 
    NOTIFY_PETS = {},
    NOTIFY_PETS_WEIGHT = {},
    DISCORD_ID = "",
    WEBHOOK_NOTE = "",
    SHOW_WEBHOOK_USERNAME = false,
    SHOW_WEBHOOK_JOBID = false,
    KICK_AFTER_GIFT_PET = false,
    GIFT_USERNAME = {},
    GIFT_PET = {},
}

